name: SSH Deploy

on:
  push:
    branches:
      - main

jobs:
  ssh-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Install expect
        run: sudo apt-get update && sudo apt-get install -y expect

      - name: Perform SSH operations
        run: |
          expect << EOF
          spawn ssh -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}
          expect "password:"
          send "${{ secrets.SSH_PASSWORD }}\r"
          expect "$ "
          send "cd ${{ secrets.REPO_PATH }}\r"
          expect "$ "
          send "git pull\r"
          expect "$ "
          send "exit\r"
          expect eof
